---
title: "Swap Performance"
output:
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: scroll
params:
  pair: "RMRK:TAI"
  xdays: 14
  madays: 7
  
---

```{css custom2, echo=FALSE}
.dataTables_scrollBody {
    max-height: 100% !important;
}
```

```{r init, include=FALSE}

library(rmarkdown)
library(flexdashboard)
library(dygraphs)


xdays <- params$xdays
madays <- params$madays
pair <- params$pair

if (pair == "ALL") {
  resx <- swaps[date >= max(swaps$date) - xdays]
    tvl <- swaps2[, sum(tvlUSD), by = date] %>%
      setnames(c("date","V1"), c("Date","tvlUSD"))
} else {
  resx <- swaps[pair1==params$pair | pair2==params$pair | pair3==params$pair & date >= max(swaps$date) - xdays]
    tvl <- swaps2[pair == params$pair, tvlUSD, by = date] %>% 
      setnames("date","Date")
}

# Helper function to concat
`%+%` <- function(a, b) paste0(a, b)

# helper function to color the bars in the charts (green, red)
getColor <- function(status) ifelse(status >= 1, "green", "red")

# helper function for chart text
getText <<- function(x, madays) {
  if (is.na(x)) return(" history too short.")
  if (x < 1) {
    txt <- " down " %+% as.character(round((x - 1) * 100, 0)) %+% "% vs. " %+% madays %+% "D Avg"
  } else {
    txt <- " up " %+% as.character(round((x - 1) * 100, 0)) %+% "% vs. " %+% madays %+% "D Avg"
  }
  txt
}

```

# Swaps {.tabset}
Row
----

### Daily Active Users

```{r}

  activeUsers <- resx[!duplicated(accountId), .N, by = date] %>%
    setnames(c("Date","Active Users"))

  u_list <<- activeUsers$`Active Users`
  activeUsers[, Average := frollmean(`Active Users`, madays)]  
  
  activeUsersAvg <- tail(activeUsers$Average, 1)
  activeUsersStatus <<- round(tail(activeUsers$`Active Users`, 1) / activeUsersAvg,2)

  add1 <- tail(activeUsers, 1)
  add1[, Date := Date + 1]
  activeUsers <- rbind(activeUsers, add1)
  
  if (nrow(activeUsers) > 5) {
    dygraph(activeUsers, main = "Active Users" %+% getText(activeUsersStatus, madays))  %>%
      dySeries("Active Users", stepPlot = TRUE, fill = TRUE, color = getColor(activeUsersStatus)) %>%
      dySeries("Average", color = "blue")
  }  

```

### Daily Trades

```{r}

  trades <- resx[, .N, by = date] %>%
    setnames(c("Date","Trades"))

  t_list <<- trades$Trades
  trades[, Average := frollmean(`Trades`, madays)]  
  
  tradesAvg <- tail(trades$Average, 1)
  tradesStatus <<- round(tail(trades$Trades, 1) / tradesAvg,2)

  add1 <- tail(trades, 1)
  add1[, Date := Date + 1]
  trades <- rbind(trades, add1)
  
  if (nrow(trades) > 5) {
    dygraph(trades, main = "Trades" %+% getText(tradesStatus, madays))  %>% 
      dySeries("Trades", stepPlot = TRUE, fill = TRUE, color = getColor(tradesStatus)) %>%
      dySeries("Average", color = "blue") 
  }
  
```

Row 
----

### Daily Trades Per User

```{r}

  activeUsers <- resx[!duplicated(accountId), .N, by = date] %>%
    setnames(c("Date","Active Users"))
  
  trades <- resx[, .N, by = date] %>%
    setnames(c("Date","Trades"))

  avgTrade <- merge(trades, activeUsers, by = 'Date')
  avgTrade[, `Trades per user` := round(Trades / `Active Users`, 1)]
  
  p_list <<- avgTrade$`Trades per user`
  avgTrade[, `Average` := frollmean(`Trades per user`, madays)]  
  
  avgTradeAvg <- tail(avgTrade$Average, 1)
  avgTradeStatus <<- round(tail(avgTrade$`Trades per user`, 1) / avgTradeAvg,2)

  avgTrade[, Trades := NULL]
  avgTrade[, `Active Users` := NULL]

  add1 <- tail(avgTrade, 1)
  add1[, Date := Date + 1]
  avgTrade <- rbind(avgTrade, add1)
  
  if (nrow(avgTrade) > 5) {
    dygraph(avgTrade, main = "Trades Per User" %+% getText(avgTradeStatus, madays))  %>% 
      dySeries("Trades per user", stepPlot = TRUE, fill = TRUE, color = getColor(avgTradeStatus)) %>%
      dySeries("Average", color = "blue") 
  }
  
```

### Daily Fees in USD

```{r}

  fees <- resx[, sum(fee), by = date] %>%
    setnames(c("Date","Swap Fees"))

  # u_list <<- activeUsers$`Active Users`
  fees[, `Average` := frollmean(`Swap Fees`, madays)]  
  
  feesAvg <- tail(fees$Average, 1)
  feesStatus <<- round(tail(fees$`Swap Fees`, 1) / feesAvg,2)

  add1 <- tail(fees, 1)
  add1[, Date := Date + 1]
  fees <- rbind(fees, add1)
  
  if (nrow(fees) > 5 & max(fees$`Swap Fees`) > 0) {
    dygraph(fees, main = "Swap Fees" %+% getText(feesStatus, madays))  %>% 
      dySeries("Swap Fees", stepPlot = TRUE, fill = TRUE, color = getColor(feesStatus)) %>%
      dySeries("Average", color = "blue") 
  }
  
```

Row
---

### Daily Trading Volume

```{r}

  tradeVolume <- resx[, sum(volumeUSDFloat), by = date] %>%
    setnames(c("Date","Trading Volume"))
  
  v_list <<- tradeVolume$`Trading Volume`
  tradeVolume[, `Average` := frollmean(`Trading Volume`, madays)]  
  
  tradeVolumeAvg <- tail(tradeVolume$Average, 1)
  tradeVolumeStatus <<- round(tail(tradeVolume$`Trading Volume`, 1) / tradeVolumeAvg,2)

  add1 <- tail(tradeVolume, 1)
  add1[, Date := Date + 1]
  tradeVolume <- rbind(tradeVolume, add1)
  
  if (nrow(tradeVolume) > 5 & max(tradeVolume$`Trading Volume`) > 0) {
    dygraph(tradeVolume, main = "Trading Volume" %+% getText(tradeVolumeStatus, madays))  %>% 
      dySeries("Trading Volume", stepPlot = TRUE, fill = TRUE, color = getColor(tradeVolumeStatus)) %>%
      dySeries("Average", color = "blue") 
  }
  
```

### Daily Volume / Total Value Locked Ratio

```{r}

  tradeVolume <- resx[, sum(volumeUSDFloat), by = date] %>%
    setnames(c("Date","Trading Volume"))
  tvl <- merge(tradeVolume, tvl, by ="Date")
  tvl[, "Volume To TVL" := `Trading Volume` / tvlUSD]
   
  tvl[, `Average` := frollmean(`Volume To TVL`, madays)]  
  
  volumeToTVLAvg <- tail(tvl$Average, 1)
  volumeToTVLStatus <<- round(tail(tvl$`Average`, 1) / volumeToTVLAvg,2)

  tvl[, `Trading Volume` := NULL]
  tvl[, `tvlUSD` := NULL]

  tvl[, Average := NULL]
  
  if (nrow(tvl) > 5) {
    dygraph(tvl, main = "Volume To TVL" %+% getText(volumeToTVLStatus, madays))  %>% 
      dySeries("Volume To TVL", color = getColor(volumeToTVLStatus)) 
  }
  
```

# Liquidity {.tabset}

### Liquidity Trend

```{r}

  if (params$pair == "ALL") {
    l <- dcast(liq, Date ~ type, value.var = 'volumeUSD')
  } else {
    l <- try(dcast(liq2[pair == params$pair], Date ~ type, value.var = 'volumeUSD'), silent = TRUE)
  }

  if (!inherits(l, "try-error")) {
    l[is.na(addLiquidity), addLiquidity := 0]
    l[is.na(removeLiquidity), removeLiquidity := 0]
    
    l[, Net := addLiquidity + removeLiquidity]
  
    add1 <- tail(l, 1)
    add1[, Date := Date + 1]
    l <- rbind(l, add1)
  
    if (nrow(l) > 5) {
      dygraph(l, main = params$pair %+% " - Liquidity Trend (USD)") %>%
        dySeries("addLiquidity", stepPlot = TRUE, fill = TRUE, color = "green") %>%
        dySeries("removeLiquidity", stepPlot = TRUE, fill = TRUE, color = "red") %>%
        dySeries("Net", color = "blue") 
    }
  }

```

# Loans {.tabset}

Row
---

### Deposit Trend

```{r}

# dailyLoanCollateral <- getLoansDailyCollateralQuery(loan_endpoint, window)
# dailyLoanPositions <- getLoansDailyPositionsQuery(loan_endpoint, window)
# collaterParams <- getLoansCollateralParamsQuery(loan_endpoint)

  pos <- merge(dailyLoanPositions, collaterParams, by="collateral.id", all=FALSE) # ignore taiKSM
  pos[, Ratio := depositVolumeUSD/debitVolumeUSD]
  pos[, Status := 'Safe']
  pos[Ratio <= requiredCollateralRatio, Status := 'Warning']
  pos[Ratio <= 1.1 * liquidationRatio, Status := 'Danger']
  
  pos <- pos[, .(Date, owner.id, collateral.id, depositVolumeUSD, debitVolumeUSD, Ratio, Status,
                 liquidationRatio, requiredCollateralRatio)]

  if (params$pair == "ALL") {
    
    tmp <- dailyLoanCollateral[, .(Date, depositChangedUSD, debitChangedUSD, txCount )]
    tmp <- tmp[, .(sum(depositChangedUSD), sum(debitChangedUSD), sum(txCount)), by = Date] %>%
      setnames(c('Date', 'depositChangedUSD', 'debitChangedUSD', 'txCount'))
    tag <- "ALL"
    
  } else {
    
    tag <- strsplit(p, ":")[[1]][1]
    tmp <- dailyLoanCollateral[collateral.id == tag, .(Date, depositChangedUSD, debitChangedUSD, txCount )]
    pos <- pos[collateral.id == tag]
    
  }

  if (nrow(pos) > 0 & !inherits(tmp, "try-error")) {

    depositStatus <- dcast(pos, Date ~ Status, fun.aggregate = sum, value.var = 'depositVolumeUSD')
    debitStatus <- dcast(pos, Date ~ Status, fun.aggregate = sum, value.var = 'debitVolumeUSD')

    add1 <- tail(tmp, 1)
    add1[, Date := Date + 1]
    tmp <- rbind(tmp, add1)
  
    if (nrow(tmp) > 5) {
      
      p1 <- dygraph(tmp[, .(Date, depositChangedUSD)], main = tag %+% " - Deposit Trend (USD)") %>%
        dySeries("depositChangedUSD", stepPlot = TRUE, fill = TRUE, color = "green")

      p2 <- dygraph(tmp[, .(Date, debitChangedUSD)], main = tag %+% " - Debit Trends (USD)") %>%
        dySeries("debitChangedUSD", stepPlot = TRUE, fill = TRUE, color = "red")
      
      p3 <- dygraph(tmp[, .(Date, txCount)], main = tag %+% " - Number of Transactions (USD)") %>%
        dySeries("txCount", color = "blue") 

      p4 <- dygraph(depositStatus, main = tag %+% " - Deposit Status") %>% 
        dyStackedBarChart()
      
      p5 <- dygraph(debitStatus, main = tag %+% " - Debit Status") %>% 
        dyStackedBarChart()
      
    } else {
      p1 <- p2 <- p3 <- p4 <- p5 <- "No Data Available."
    }
    
  }

  p1

```
### Debit Trend

```{r}
p2
```

Row
---

### Transactions

```{r}
p3
```

Row
---

### Deposit Status

```{r}
p4
```

### Debit Status

```{r}
p5
```

# Risky Loans {.tabset}

### Top 5 Risky Loans

```{r}

if (nrow(pos) > 0 ) {
  
  setorder(pos, Ratio)
  top5 <- pos[!is.nan(Ratio), .(Date, owner.id, collateral.id, depositVolumeUSD, debitVolumeUSD, Ratio, requiredCollateralRatio)][1:5]
  
  mutate_if(top5, is.numeric, function(x) {cell_spec(x=round(x,2))}) %>%
  kable(escape = FALSE, align = "r") %>%
  kable_styling(c("striped", "condensed"), full_width = FALSE)

} else {
  
  print("No Data Available.")
  
}
```
